image: mcr.microsoft.com/dotnet/sdk:7.0
stages:
  - test
  - deploy

test:
  stage: test
  script: 
    - "dotnet test"
  except:
    - tags

deploy_lib:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:7.0
  only:
    - tags
  script:
    - dotnet pack -p:PackageVersion=$CI_COMMIT_TAG ./source/GeneratedResourceClient.csproj --output ./nupkgs  --include-symbols
    - dotnet nuget push -s ${PUBLIC_NUGET_NNTC} -k ${PUBLIC_NUGET_KEY_NNTC} nupkgs/*.nupkg
